### ISSUE TITLE
Help pls

### ISSUE THREAD

**Issue by b-7307** [Z3NTL3/Anti-Cursed-Darkness-Squad-BETA#15]
Hello, nice script! 
Whats the best way for attack a normal https site 
Install works fine but it doesn't seem to work

Already thanks

**Comment by Z3NTL3** [comment]
"Doesn't seem to work". 

So that's why this project has over 4.000 users in a short time?

Your attack depends on a free proxy pool. Even with this free proxy pool you can down a lot sites. Also it depends on your own machine power.

Also you can check the proofs mentioned.

In the future we look forward to add over 2.000.000 reverse proxy ip pool if we get financed via donations for this project.

But for now don't worry. This panel is using already verry good methods and downed a lot major sites, stressers and stuff like that. It's good for now, for a free proxy using panel.

Best methods which are legit:
ultra-bypass
nuker-proxyless
http-raw
nuker-proxied

**Comment by b-7307** [comment]
I didn't mean to offend you but it doesn't work when I use pyflooder the site is down right away with you not!
Greetz

**Comment by Z3NTL3** [comment]
> I didn't mean to offend you but it doesn't work when I use pyflooder the site is down right away with you not!
> Greetz

There are enough methods, the method to use depends on the site you attack. If you don't liked it then just go away and don't use it. Simple as that. We have enough users who liked it.

**Comment by b-7307** [comment]
Buddy, of course I'm leaving cause I can't use it. I'd rather give you a star. I do like it otherwise I wouldn't message you. I wanted to know how to use it properly because it simply doesn't work here

**Comment by Z3NTL3** [comment]
> Buddy, of course I'm leaving cause I can't use it. I'd rather give you a star. I do like it otherwise I wouldn't message you. I wanted to know how to use it properly because it simply doesn't work here

"Doesn't work" don't blame any tool or something if your vps is just bad. And yeah go away and don't use it.
