### ISSUE TITLE
Questions and suggestions in the process of use

### ISSUE THREAD

**Issue by dauifu** [Z3NTL3/Anti-Cursed-Darkness-Squad-BETA#5]
Thank you for your project, It's easy to use,But I encountered the following problems in the process of using
1. http-root and http-vip methods Power too small, My Server 16x Core 32G RAM 10Gbps Network, but net/out only <2M/s , I test my network from speedtest Down/up it can reach 9500± Mbps, so I think my network no problem

2. ultra-bypass method. CF UAM or CAPTCHA cannot be recognized :) sometimes

I recommend sticking with darkness.py instead of using binaries, Because I want to change the API for getting the proxy
For example, I need to get the agent whose country is JP and status is Alive

thanks

**Comment by Z3NTL3** [comment]
# Intro
Hey,

Thanks for your message.

# Answers for your first question
http-vip , http-root are the least powerful scripts , we will update them soon.

ultra-bypass works by finding a server's privacy pass, if it can't find it it can't bypass Cloudflare either. As soon as ultra-bypass doesn't work, I recommend using cf-bypass or website-nuker-https.

On a cloud shell of 100-200mbps, website-nuker-https had a reqeust speed of 120.000/second, but cf-bypass would be more powerful, depends on the server. Just test these methods one by one (ultra-bypass, cf-bypass & website-nuker-https).

The most powerful layer 7 scripts are ultra-bypass , cf-bypass and website-nuker-https. All of these three bypass Cloudflare. As soon as 1 of this method does not work, for example ultra-bypass (for example: because there is no privacy pass) then I advise you to use cf-bypass or website-nuker-https.

# Answer for your second question
I will make the proxy crawler extra advanced where you can choose from which country the proxies should be.

I will also remove automatic proxy crawling during startup so you can edit proxies.txt in your own proxies, once you don't have it just type proxy crawl in the panel.

I plan to get this done tomorrow.
